### ISSUE TITLE
Error when there are too many Asteroids

### ISSUE THREAD

**Issue by Drew-Wagner** [Drew-Wagner/Meteor-Storm#4]
Traceback (most recent call last):
  File "C:\Users\e6430\Documents\GitHub\Meteor-Storm\asteroids.py", line 371, in <module>
    manager.update()
  File "C:\Users\e6430\Documents\GitHub\Meteor-Storm\asteroids.py", line 253, in update
    self.state.update()
  File "C:\Users\e6430\Documents\GitHub\Meteor-Storm\asteroids.py", line 211, in update
    a.update()
  File "C:\Users\e6430\Documents\GitHub\Meteor-Storm\asteroids.py", line 350, in update
    self.draw()
  File "C:\Users\e6430\Documents\GitHub\Meteor-Storm\asteroids.py", line 359, in draw
    self.gm.roids.remove(self)
ValueError: list.remove(x): x not in list

**Comment by Drew-Wagner** [comment]
I think it has to do with an asteroid exploding at the same time as it goes below the screen...
